version: '3'

services:
  
  # the remote desktop proxy which the web application communicates with.
  guacd:
    container_name: guacamole_guacd
    image: guacamole/guacd
    restart: always

  # the database that stores authentication and connection information.
  db:
    container_name: guacamole_db
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  # the HTML5 web application which serves the Guacamole client to users.
  webserver:
    container_name: guacamole_webserver
    image: guacamole/guacamole:0.9.14
    depends_on:
      - db
      - guacd
    ports:
        - "8080:8080"
    environment:
      - GUACD_HOSTNAME=${GUACD_HOSTNAME}
      - GUACD_PORT=${GUACD_PORT}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always